LeadManagementProject/force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Object to store countries information from external API</description>
    <label>Country</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LeadManagementProject/force-app/main/default/objects/Country__c/fields/Alpha3Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha3Code__c</fullName>
    <description>ISO Country code - 3 letters</description>
    <label>Alpha3Code</label>
    <length>3</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

LeadManagementProject/force-app/main/default/objects/Country__c/fields/Capital__c.field-meta.xml
<CustomField>
    <fullName>Capital__c</fullName>
    <description>Capital city name</description>
    <label>Capital</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LeadManagementProject/force-app/main/default/objects/Country__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>World region</description>
    <label>Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LeadManagementProject/force-app/main/default/objects/Lead/fields/CountryCapital__c.field-meta.xml
<CustomField>
    <fullName>CountryCapital__c</fullName>
    <description>Lead Country Capital</description>
    <label>Country Capital</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LeadManagementProject/force-app/main/default/objects/Lead/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <description>Lead Country Code</description>
    <label>CountryCode</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

LeadManagementProject/force-app/main/default/objects/Lead/fields/CountryRegion__c.field-meta.xml
<CustomField>
    <fullName>CountryRegion__c</fullName>
    <description>Lead Country Region</description>
    <label>Country Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LeadManagementProject/force-app/main/default/classes/LeadTriggerHandlerTest.cls
@isTest
public class LeadTriggerHandlerTest { 

    @isTest
    static void testBeforeInsertUpdate() {
        Country__c testCountry = new Country__c(
            Name = 'TestCountry',
            Region__c = 'TestRegion',
            Alpha3Code__c = 'TST',
            Capital__c = 'TestCapital'
        );
        insert testCountry;

        Lead testLeadValid = new Lead(
            FirstName = 'John',
            LastName = 'Donut',
            Country = 'TestCountry',
            Company = 'John Donut'
        );

        Lead testLeadInvalid = new Lead(
            FirstName = 'Scarlet',
            LastName = 'Switch',
            Country = 'InvalidCountry',
            Company = 'Scarlet Switch'
        );

        List<Lead> testLeads = new List<Lead>{ testLeadValid, testLeadInvalid };

        Test.startTest();
            insert testLeads;
        Test.stopTest();

        testLeadValid = [SELECT CountryRegion__c, CountryCode__c, CountryCapital__c FROM Lead WHERE Id = :testLeadValid.Id];
        testLeadInvalid = [SELECT CountryRegion__c, CountryCode__c, CountryCapital__c FROM Lead WHERE Id = :testLeadInvalid.Id];

        Assert.areEqual(null, testLeadInvalid.CountryRegion__c);
        Assert.areEqual(null, testLeadInvalid.CountryCode__c);
        Assert.areEqual(null, testLeadInvalid.CountryCapital__c);
    }
}