LeadManagementProject/force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Object to store countries information from external API</description>
    <label>Country</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LeadManagementProject/force-app/main/default/objects/Country__c/fields/Alpha3Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha3Code__c</fullName>
    <description>ISO Country code - 3 letters</description>
    <label>Alpha3Code</label>
    <length>3</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

LeadManagementProject/force-app/main/default/objects/Country__c/fields/Capital__c.field-meta.xml
<CustomField>
    <fullName>Capital__c</fullName>
    <description>Capital city name</description>
    <label>Capital</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LeadManagementProject/force-app/main/default/objects/Country__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>World region</description>
    <label>Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LeadManagementProject/force-app/main/default/objects/Lead/fields/CountryCapital__c.field-meta.xml
<CustomField>
    <fullName>CountryCapital__c</fullName>
    <description>Lead Country Capital</description>
    <label>Country Capital</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LeadManagementProject/force-app/main/default/objects/Lead/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <description>Lead Country Code</description>
    <label>CountryCode</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

LeadManagementProject/force-app/main/default/objects/Lead/fields/CountryRegion__c.field-meta.xml
<CustomField>
    <fullName>CountryRegion__c</fullName>
    <description>Lead Country Region</description>
    <label>Country Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LeadManagementProject/force-app/main/default/classes/LeadTriggerHandler.cls
/**
 * @description       : Trigger Handler for Lead Object
 * @author            : Miguel Garcia 
 * Modifications Log
 * 1.0   21.08.2024   Miguel Garcia                        Initial version.
**/
public class LeadTriggerHandler {

    public void beforeInsertUpdate(List<Lead> newLeads) {
        Set<String> countries = new Set<String>();
    
        for (Lead lead : newLeads) {
            if (String.isNotBlank(lead.Country)) {
                countries.add(lead.Country);
            }
        }
        Map<String, Country__c> countryMap = new Map<String, Country__c>(
            [SELECT Name, Region__c, Alpha3Code__c, Capital__c 
             FROM Country__c 
             WHERE Name IN :countries]
        );
        
        for (Lead lead : newLeads) {
            if (countryMap.containsKey(lead.Country)) {
                Country__c countryInfo = countryMap.get(lead.Country);
                lead.CountryRegion__c = countryInfo.Region__c;
                lead.CountryCode__c = countryInfo.Alpha3Code__c;
                lead.CountryCapital__c = countryInfo.Capital__c;
            } else {
                if (String.isNotBlank(lead.Country)){
                    try {
                        //Call the API to retrieve the releted info
                        Map<String, Object> countryData = CountryLayerHandler.getCountryDataByName(lead.Country);

                        if (countryData != null) { 
                            lead.CountryCapital__c = countryData.get('capital').toString();
                            lead.CountryCode__c = countryData.get('alpha3Code').toString();
                            lead.CountryRegion__c = countryData.get('region').toString();
                        }
                    } catch (Exception exc) {
                        System.debug(LoggingLevel.ERROR, lead.Country + ' - Exception: ' + exc.getMessage());
                    } 
                }
            }
        }
    }
}