LeadManagementProject/force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <description>Object to store countries information from external API</description>
    <label>Country</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LeadManagementProject/force-app/main/default/objects/Country__c/fields/Alpha2Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha2Code__c</fullName>
    <description>ISO Country code - 2 letters</description>
    <label>Alpha2Code</label>
    <length>2</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

LeadManagementProject/force-app/main/default/objects/Country__c/fields/Alpha3Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha3Code__c</fullName>
    <description>ISO Country code - 3 letters</description>
    <label>Alpha3Code</label>
    <length>3</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

LeadManagementProject/force-app/main/default/objects/Country__c/fields/Capital__c.field-meta.xml
<CustomField>
    <fullName>Capital__c</fullName>
    <description>Capital city name</description>
    <label>Capital</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LeadManagementProject/force-app/main/default/objects/Country__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>World region</description>
    <label>Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

LeadManagementProject/force-app/main/default/objects/Country__c/fields/RegionalBlocs__c.field-meta.xml
<CustomField>
    <fullName>RegionalBlocs__c</fullName>
    <description>Regional blocks in which the country is a member</description>
    <label>RegionalBlocs</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SAARC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

LeadManagementProject/force-app/main/default/classes/CountryLayerHandlerTest.cls
@isTest
public class CountryLayerHandlerTest {
    
    @testSetup
    static void setup() {
        Country__c country = new Country__c(Name = 'Australia',
                                            Capital__c = 'Canberra', 
                                            Alpha2Code__c = 'AU', 
                                            Alpha3Code__c = 'AUS', 
                                            Region__c = 'Oceania', 
                                            RegionalBlocs__c = 'APEC');
        insert country;
    }

    @isTest
    static void testCountryUpdate() {
        Test.setMock(HttpCalloutMock.class, new CountryLayerMockResponse());
        
        Test.startTest();
            CountryLayerHandler.updateCountryInformation();
        Test.stopTest();

        Country__c updatedCountry = [SELECT Capital__c FROM Country__c WHERE Name = 'Australia'];
        Assert.areEqual('Canberra', updatedCountry.Capital__c, 'The capital should be updated to Canberra.');
    }

    @isTest
    static void testCountryUpdateWithApiError() {
        Test.setMock(HttpCalloutMock.class, new CountryLayerMockErrorResponse(400));
        
        Test.startTest();
        
        try {
            CountryLayerHandler.updateCountryInformation();
        } catch (System.CalloutException e) {
            Assert.isTrue(e.getMessage().contains('400'), 'Error code should be in the exception message.');
        }
        
        Test.stopTest();
    }

    public class CountryLayerMockResponse implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('[{"name":"Australia","capital":"Canberra","alpha2Code":"AU","alpha3Code":"AUS","region":"Oceania","regionalBlocs":[{"acronym":"ASEAN"}]}]');
            res.setStatusCode(200);
            return res;
        }
    }

    public class CountryLayerMockErrorResponse implements HttpCalloutMock {
        private Integer statusCode;

        public CountryLayerMockErrorResponse(Integer statusCode) {
            this.statusCode = statusCode;
        }

        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            
            String errorBody = '{"success": false, "error": {"code": 400, "type": "400_bad_request", "info": "Unhandled Error"}}';
            res.setBody(errorBody);
            res.setStatusCode(statusCode);
            return res;
        }
    }
}